version: '3.7'

services:
  flask:
    build: 
      context: ./services/
      dockerfile: ./flask_app/Dockerfile
    container_name: flask_server
    #platform: linux/amd64
    #command: gunicorn --bind 0.0.0.0:5000 app:app
    command: python3 app.py
    volumes:
      - static:/home/app/flask_app/static
    expose:
      - 5000
    env_file:
      - ./.env.dev
  
  db:
    restart: always
    image: postgres:latest
    container_name: mlflow_db
    expose:
        - ${DB_PORT}
    environment:
        - POSTGRES_PASSWORD=${DB_PW}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_DB=${DB_NAME}
    volumes:
        - db_datapg:/var/lib/postgresql/data

  nginx:
    restart: always
    build: ./services/nginx
    container_name: nginx_server
    volumes:
      - static:/home/app/flask_app/static
    ports:
      - "80:80"
    depends_on:
      - flask

  mlflow:
    build:
      context: ./services/mlflow
    container_name: mlflow_server
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: mlflow server 
      --backend-store-uri postgresql://${DB_USER}:${DB_PW}@db:${DB_PORT}/${DB_NAME}
      --default-artifact-root s3://made-classifier-food-type/mlflow/
      --host 0.0.0.0 
      --port 4040
    volumes:
      - backend:/backend
    ports:
      - "4040:4040"

volumes:
  static:
  backend:  
  db_datapg:
        
