
# @package _global_

defaults:
  - _self_ 
  - model: naive_bayes.yaml
  - experiment: null


  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog


mlflow:
  # tracking_uri: file://project_made/train_pipeline/mlruns
  tracking_uri: http://madeclassifirefoodtype.ru:4040/
  experiment_name: "default"
  
seed: 0

load_data:
  in_path: data/menu_df_for_made.pkl
  out_path: data/load_data.csv

test_data_path: data/golden_set_custom.csv

valid_split:
  val_size: 0.2

preprocess_cache: True
preprocess:
  _target_: preprocess.transform_pipeline.PreprocessNameDesc
  to_spell_path: project_made/preprocess/to_spell.npy
  threshold_cnt: 10

inference_path: /tmp/model.pkl


