
# @package _global_

defaults:
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog


mlflow:
  tracking_uri: http://madeclassifirefoodtype.ru:4040/
  experiment: naive_bayes


load_data:
  in_path: data/menu_df_for_made.pkl
  out_path: data/load_data.csv

test_split:
  test_size: 0.1

train_reduce:
  class_max_len: 10000

valid_split:
  val_size: 0.3

preprocess:
  _target_: preprocess.transform_pipeline.PreprocessTransformer

  to_spell_path: project_made/preprocess/to_spell.npy
  max_len: 10000

model:
  _target_: model.naive_bayes.TfidfComplementNB


